### ISSUE TITLE
Ad removal issue in new skype version

### ISSUE THREAD

**Issue by TymonKinneas** [dlehn/Skype-Utility-Project#16]
The advertisement removal doesn't seem to work in the new version skype version 7.3.0.101 properly. Advertisements will 'appear' later on when a window is left open for a period of time now.

**Comment by dlehn** [comment]
Oh those sneaky bastards, I bet they're breaking my stuff on purpose. I'll try to reproduce it and see what I can do.  
Any idea about how long it will generally take before the ads show up? And are you using the combined or split window view?  

**Edit**: Had the window open for an hour now in combined view, nothing so far.

**Comment by TymonKinneas** [comment]
I'm in split window view. I'm not sure if this helps but when the advertisements pop up, if I disable the view ads, then re-enable it, the ad disappears as long as I keep the window open. If I reopen it, the ad will reappear. I'd say it happens between 5-15 minutes give or take. I'm not sure if it being loaded in to combined view and then loading split view fixes the problem, but, to recreate it...at least for my computer... Have skype in split window view, if you were from combined and switched, perhaps close out of skype and restart it. You should end up with ads in your chat windows then... if not, then something must be screwed up with my skype install and I might have to completely uninstall/reinstall it.

**Comment by dlehn** [comment]
Huh, I've played around with this for quite some time now, and I have been able to make an ad show up exactly once. That means the problem is not just on your side, but it's probably going to be a pain in the ass to fix.  
This may take a while. Until then, you should also be able to make the ads disappear by simply resizing the affected window, e.g. maximizing and restoring it (no need to toggle the hide ads option off/on).

Just to make sure: I assume you're using the latest version of SUP (1.3.6), right?

**Comment by TymonKinneas** [comment]
Yup. 1.3.6. Glad to know it's not just my problem though. also glad to know resizing it is a quick fix. hmm. It's weird that you're only getting an ad once though. I get them every single darn window every single time. It's annoying. Microsoft Forced me onto Skype when they discontinued live messenger, which I genuinely preferred for a variety of reasons, (free text messaging and email notification just to scratch the surface...), and now they think they're entitled to make money off cramming ads into the client that use my bandwidth that they are not helping to pay for? I know it seems overly dramatic, but I only get so much bandwidth a month, so even 4 mb used for ads is 4 mb that I do not get. >:

**Comment by dlehn** [comment]
I know exactly what you mean, I don't like Skype either. It was alright when they still had the third-party API, so I could simply use it in Trillian, but the Skype client itself sucks. I'm always trying to convince my contacts to switch to Trillian, but it's always the same "but everyone else is using Skype" answer.  

Also, as a side note, I should tell you that SUP's "Hide Ads" option will unfortunately _not_ prevent the Skype Ads from using up traffic. SUP only tries to hide them, it will not prevent them from being downloaded. I tried removing the ads completely, but that would always cause Skype to crash.  
If you really need that traffic, you can follow [these instructions](http://www.cnet.com/how-to/how-to-disable-ads-in-skype/) to prevent Skype from downloading them altogether. This would still leave an empty banner at the top of each conversation window, but that's why we have SUP. :wink:

**Comment by dlehn** [comment]
Okay so it's been a while since I said something, because the weather over here has been really great the last few days and I just couldn't be arsed to spend my time in front of the computer when I could just as well be lying outside in the sun like the lazy bastard I am.  

Now, I still really have no clue what causes this issue and it happened to me exactly once today (after a few hours of using Skype) and a friend of mine also had this problem, but there don't seem to be any fixed circumstances in which it will always happen.

So, for the moment, all I can do is speculate and try out some fixes. But I can't really tell if they work because the bug happens so rarely in the first place.  
I have tried to change some things which could resolve the issues (or make things even worse, who knows), and I would be grateful if you could help me test them. Simply download the file linked below, use it instead of the regular 1.3.6 `dll` and tell me if you still see any ads popping up.  
http://s000.tinyupload.com/?file_id=43266826541386754913

**Comment by Kekkonshiki** [comment]
i've tested it for v7.3.59.101 - all is ok!

**Comment by dlehn** [comment]
Great, thank you! I couldn't find any problems either, so I'll just assume that the problem is fixed.  
Now I can make this an official release so everybody can get it.
