### ISSUE TITLE
Plugin menu location

### ISSUE THREAD

**Issue by nestdimon** [dlehn/Skype-Utility-Project#3]
It would be great if plugin's menu items were placed into **View** _(exists)_ -> **Advanced** _(need to create)_ -> **(plugin submenu)**.
Current menu **Util** is not clear for user.

**Comment by dlehn** [comment]
I'm not sure how to do this reliably, since we don't have access to Skype's menu IDs.
We could only look for the **View** menu item by name, which we would have to hard-code for each language. (At least I'm not aware of any other way.)
Another way would be to look for the menu ID manually in, say, the English version and then hard-code the found ID into the plugin, assuming it will be the same for all languages. This could however break in any subsequently released Skype version if they decide to change their menu IDs.

Any suggestions?

For the time being, the menu name "Util" could simply be replaced with "SUP", that might be less ambiguous.

**Comment by nestdimon** [comment]
Application's menu handle can be obtained with `HWND GetSubMenu(HWND menu, UINT position)` and id with `GetMenuItemID(HWND menu, int position)`, it's not a problem. I've made some experiments and found that _only when UI language is not english_, Skype refill submenu items when user expand it. So we can't attach custom submenu just once. But it is possible to reattach submenu after Skype window dispatch WM_INITMENUPOPUP message.

I've got menu ids:
0x45 Skype
0x46 Contacts
0x47 Call
0x48 Conversation
0x49 View
0x4A Tools
0x4B Help

I'll send you a pull request today with working attach to Skype `View` menu.

**Comment by dlehn** [comment]
Merged your pull request in 602becd, but changed it to attach to the "Tools" menu instead of "View" since that (in my opinion) fits better. If you disagree, just open a new issue.  
Also, please take a look at the Russian translation of "Advanced" (`IDS_MAINMENU` in the Russian string table), I have no idea if that's correct.

**Comment by nestdimon** [comment]
You are fast! Thanks for accepting my changes. And yes, "Tools" is better place for menu)
It would be better to translate as `&Дополнительно [SUP]`.

**Comment by dlehn** [comment]
All right, fixed the translation. I'll create a new compiled release once we have settled on #4.
