### ISSUE TITLE
Invert "Hide..." submenu check logic

### ISSUE THREAD

**Issue by nestdimon** [dlehn/Skype-Utility-Project#4]
Current Layout submenu items:
(x) Hide Ads
(x) Hide Home Toolbar
(x) Hide Identity Panel
When user want to hide all of these, menuitems need to be checked. It's annoying. 

Better wolud be to invert logic and titles:
( ) Show Ads
( ) Show Home Toolbar
( ) Show Identity Panel
This way is better because user need to uncheck menu to hide UI element.

**Comment by dlehn** [comment]
I actually thought about that when I made the menus.  

My reasoning was, that any option causing Skype to behave in a way not intended by the developers should be explicitly recognizable as such. Also, any such option is disabled by default, forcing the user to consciously turn it on.  
This makes it easier to see at first glance, which of the plugin's options have been activated and might cause things to work differently from what the user is used to (I know a lot of people who immediately get scared when a program starts doing something they're not used to, so this is a valid concern).

Also, since you are probably not going to change these options very often, I don't think this has any relevant impact on the plugin's usability.

**Comment by nestdimon** [comment]
And what about "Allow Chat Formatting"? Why is it checked by default? :)

Agree with you, it's like tweaks and if SUP would be a MegaTweakerSoftware I would not propose to invert logic. In my opinion, SUP allow user to access advanced options of Skype, like show some hidden menu as if Skype developers specially hide it.

**Comment by dlehn** [comment]
Well... actually you're right, that _is_ a little inconsistent.  
Anyway in this case I'd rather switch "Allow Chat Formatting" to "Disable Chat Formatting" (I didn't really like the word "allow"  in the first place) than changing the other options.

**Comment by nestdimon** [comment]
Ok, i just _suggest_ changes that in my opinion would be nice.

**Comment by dlehn** [comment]
Alright then, since we can't agree here, I'll see if we can get another opinion on this to settle the matter...

**Comment by nestdimon** [comment]
Sorry for bother you. It is not so principal. I'll agree with your decision.

**Comment by dlehn** [comment]
Not a problem, I just want to do what's best. I know I'm not perfect ;)  
But since right now we only have one voice for each version, it's hard to make a decision. I asked @kretzmoritz for an opinion, and I'll just go with whatever the majority says.  

(If anybody else is reading this, feel free to join the discussion!)

**Comment by kretzmoritz** [comment]
Personally I agree that consistency is a definite requirement: 

"My reasoning was, that any option causing Skype to behave in a way not intended by the developers should be explicitly recognizable as such. Also, any such option is disabled by default, forcing the user to consciously turn it on."

Thus the "Allow chat formatting" option should be changed to "Disable chat formatting". SUP settings are probably not changed so often, that the impact of actively having to turn them on is noticable.

**Comment by dlehn** [comment]
Alright, then I'll go with that.

In that case, @nestdimon, would you be so kind as to provide me with the correct Russian translation for the "Disable Chat Formatting" option, so I can integrate it?

**Comment by nestdimon** [comment]
Not a problem! "Disable Chat Formatting" -> "Отключить оформление сообщений"

**Comment by dlehn** [comment]
Thanks!  
This is now integrated into the new 1.3.2 release. Now I can finally close this :)
